#!/usr/bin/env bash

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd )"

function containsElement () {
  local e
  for e in "${@:2}"; do
    [[ "$e" == "$1" ]] && return 0
  done
  return 1
}

if containsElement "list-sessions" "$@"; then
  echo "Failed to connect to tmux server" 1>&2
  cat $CURR_DIR/.sessions
  exit 0
fi

quoted_args=()
for arg; do
  quoted_args+=("'$arg'")
done

echo ":::STUB_TMUX:::$(basename $PWD)> tmux ${quoted_args[@]}"
