#!/usr/bin/env bash

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd )"

function containsElement () {
  local e
  for e in "${@:2}"; do
    [[ "$e" == "$1" ]] && return 0
  done
  return 1
}

if containsElement "list-sessions" "$@"; then
  cat $CURR_DIR/.sessions
  exit 0
fi

echo ":::STUB_TMUX:::$(basename $PWD)> tmux $@"
