#!/usr/bin/env node
var fs = require('fs');
var SESSIONS = __dirname + '/.sessions'
var args = process.argv;

if(args.indexOf('list-sessions') > 0) {
  fs.createReadStream(SESSIONS).pipe(process.stdout);
} else {
  console.log("tmux " + args.splice(2).join(' '));
}
